model_settings:
  model: "LSTM" # Choose the model to be trained (currently, the code supports the DNN, RNNs (i.e., LSTM and GRU ), BiRNN (i.e., bidirectional LSTM and bidirectional GRU))
  optimizer:
    type: "sgd" # Optimizer used for training (SGD)
    #learning_rate: 0.0001                     # Learning rate for opt
  loss_function: "binary_crossentropy" # The loss function used
  model_para:
    handle_data_imbalance: True
    max_sequence_length: 1000
    embedding_dim: 100
    use_dropout: True
    dropout_rate: 0.5
    dnn_size: 128 # The number of neurons used for DNN (the first layer)
    rnn_size: 128 # The number of neurons used for RNN (the first layer)
    birnn_size: 64 # The number of neurons used for Bi-RNN (the first layer)
    embedding_trainable: False

training_settings:
  dataset_config:
    Test_set_ratio: 0.2 # If not using a separate test set, set the test set ratio.
    Validation_set_ratio: 0.2 # Use part of the training set as the validation set.
  network_config:
    batch_size: 4
    k_shot: 1
    epochs: 50
    patcience: 35
    save_training_history: True
    plot_training_history: True
    validation_metric: "val_loss"
  tokenizer_path: "w2v/SARD_4/tokenizer.pickle"
  embedding_model_path: "w2v/SARD_4/w2v_model.txt"
  save_best_model: True
  using_separate_test_set: False # If this is set to True, please specify the path of test set.
  test_set_path: "test/"
  period_of_saving: 1
  log_path: "logs/"
  model_save_path: "Models/" #没用上。当前训练好的模型被保存在 Models/ 文件夹下
  model_saved_name: "test_model_LSTM"
